CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR (45) NOT NULL,
    CLI_CPF VARCHAR (11) NOT NULL,
    CLI_EMAIL VARCHAR (50) NOT NULL,
    CLI_TELEFONE VARCHAR (9) NOT NULL
);

ALTER TABLE CLIENTE
MODIFY COLUMN CLI_CPF VARCHAR (11) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO (
	PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR (50) NOT NULL,
    PRO_DESCRICAO VARCHAR (200) ,
    PRO_PRECO DOUBLE  NOT NULL,
    PRO_QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL (
	ALU_ID 				INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL	DATE NOT NULL,
    ALU_DATA_DEVOLUCAO	DATE NOT NULL,
    VALOR_TOTAL			DOUBLE NOT NULL,
    FK_CLI_ID			INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
	ALP_ID		INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRO_ID	INT NOT NULL,
    FK_ALU_ID	INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
    FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Tobias", "59298118066", "tobias@gmail.com", "926254542");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("lucas", "87634572981", "lucas@gmail.com", "993565012");

INSERT INTO PRODUTO (PRO_NOME, PRO_PRECO, PRO_QTD_DISPONIVEL)
VALUES ("Iphone 18 pro max",600, 100);
                     
INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL)
VALUES ("Lancha Tutbo", "lancha para rio e mar", 2500, 5);

INSERT INTO ALUGUEL (ALU_DATA_ALUGUEL, ALU_DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLI_ID)
VALUES ("2026-10-08", "2026-10-15", 675, 2);

INSERT INTO ALUGUEL_PRODUTO (FK_PRO_ID, FK_ALU_ID)
VALUES (1,1);



INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Ana Silva", "12345678900", "ana.silva@gmail.com", "987654321");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Bruno Souza", "23456789011", "bruno.souza@gmail.com", "976543210");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Carla Mendes", "34567890122", "carla.mendes@example.com", "965432109");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Daniela Rocha", "40281628076", "daniela.rocha@gmail.com", "903386468");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Elaine Costa", "36533244086", "elaine.costa@gmail.com", "987608438");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Felipe Lima", "58749596020", "felipe.lima@gmail.com", "947494092");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Giselle Martins", "66578156038", "giselle.martins@gmail.com", "913217637");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Henrique Alves", "76574745055", "henrique.alves@gmail.com", "959022334");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Isabela Ferreira", "67112770076", "Isabela.ferreira@gmail.com", "919312771");

INSERT INTO CLIENTE (CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("João Oliveira", "60065390040", "joao.oliveira@gmail.com", "936721496");


INSERT INTO PRODUTO (PRO_NOME, PRO_DESCRICAO, PRO_PRECO, PRO_QTD_DISPONIVEL)
VALUES ("Notebook Dell Inspiration", "Notebook com processodor Intwl Core i7, 16GB de RAM, 512GB SSD", 450, 10),
	    ("Smartphone Samsung Galaxy S21", "Smartphone com tela de 6,2 polegadas, 128GB de Armazenamento", 350, 15),
        ("TV LG 55' 4K", "Smart TV com resolução de 4K e HDR", 280, 8),
        ("Drone DJI Phantom 4", "Drone com câmera $K e estabilização de imagem", 300, 55),
        ("Câmera Canon EOSI T7", "Câmera DSLR com lente 18-55mm, 24.1MP", 250, 2),
        ("Câmera GoPro Hero 9", "Câmera de ação com resolução 5K e resistência à água", 80, 60),
        ("Tenda Eventos 5x5m", "Tenda resistente à água e fácil de montar", 200, 4),
        ("Microfone Shure SM58", "Microfone para apresentações e shows", 40, 35),
        ("Mesa de Som Behringer", "Mesa de Som com 16 canais e efeitos integrados", 500, 3),
        ("Kit de ILuminação Fotográfica", "Kit com softbox, tripés e lâmpadas de LED", 100, 6);


SELECT 
    PRO_NOME, PRO_DESCRICAO, PRO_PRECO
FROM
    PRODUTO;
    
    
-- SELECIONAR APENAS PRODUTOS COM PREÇO MAIOR QUE 250
SELECT * FROM PRODUTO
WHERE PRO_PRECO > 250;

-- SELECIONAR APENAS PRODUTO DE ID 3
SELECT PRO_ID, PRO_NOME 
FROM PRODUTO
WHERE PRO_ID = 3;

-- SELECIONAR PRODUTOS QUE CONTENHAM NOTEBOOK EM QUALQUER PARTE DO NOME
SELECT *
FROM PRODUTO
WHERE PRO_NOME LIKE '%NOTEBOOK%';


-- ATUALIZAR A QUANTIDADE DO NOTEBOOK PARA 200
UPDATE PRODUTO
SET PRO_QTD_DISPONIVEL = 200
WHERE PRO_ID = 4; -- UPDATE PRECISA DE WHERE

-- ATUALIZAR A DESCRIÇÃO DO NOTEBOOK PARA VAZIO
UPDATE PRODUTO
SET PRO_DESCRICAO = NULL
WHERE 	PRO_ID = 4; -- UPDATE PRECISA DE WHERE

-- APAGAR (DELETAR) O NOTENOOK
DELETE FROM PRODUTO
WHERE PRO_ID = 4; -- DELETE PRECISA DE WHERE