CREATE DATABASE BD_ESTOQUE_SUPER_MERCADO;
USE BD_ESTOQUE_SUPER_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TIPO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
	CNPJ VARCHAR (14) NOT NULL PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    TELEFONE VARCHAR (100) NOT NULL
);